from PPOAgentsLosses import PPOAgentWithVanillaPolicyGradientLoss, PPOWithGeneralizedAdvantageLoss, PPOWithSurrogateLossWithoutClipping, PPOWithSurrogateLossWithClipping

agent = PPOAgentWithVanillaPolicyGradientLoss()
agent.train()
agent.plot_episodic_rewards()
agent.plot_episodic_losses()